# Site settings
baseurl = "https://laurance-george.com/"
languageCode = "en-us"
title = "Laurance George"
theme = "vncnt-hugo"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Laurance George"
    description = "A personal site"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Laurance George"

    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Laurance George"
        subtitle = "Software Engineer"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Professional"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "I am a software engineer with a specialization in finance."
        right = "In my spare time I enjoy music, getting outside, and reading a good book."

        [params.about.button]
            text = "Download CV"
            link = "//resume.com"
            icon = "download"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/el-gee"

            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "linkedin.com/laurance-george"


        [params.footer.credits]
            title = "Theme"
            text = "This theme is forked from [Freelance] (//https://github.com/el-gee/hugo-freelancer-theme)."
